name: "SystemInfo"
version: ${project.version}
main: "top.cmarco.systeminfo.plugin.SystemInfo"
authors: ["CMarco"]
api-version: 1.13
folia-supported: true
softdepend:
  - ProtocolLib
description: "SystemInfo - The Master of Server Hardware."
